name: Deploy to Ubuntu Server - Suppliers

on:
  push:
    branches:
      - Suppliers

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to Server
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF_SSH'
            cd ~/Sewnex
            git checkout Suppliers
            git pull

            # Remove old container if it exists
            if docker ps -a --format '{{.Names}}' | grep -q "^dev-sewnex-accounts$"; then
              docker rm -f dev-sewnex-suppliers
            fi

            # Create Dockerfile
            echo 'FROM node:22.11.0' > Dockerfile
            echo 'WORKDIR /usr/src/app' >> Dockerfile
            echo 'COPY package*.json ./' >> Dockerfile
            echo 'RUN npm install' >> Dockerfile
            echo 'COPY . .' >> Dockerfile
            echo 'EXPOSE 4009' >> Dockerfile
            echo 'CMD ["node", "server.js"]' >> Dockerfile

            # Build and run the container
            docker build -t dev-sewnex-suppliers .
            docker run -d --name dev-sewnex-suppliers -p 7009:4009 dev-sewnex-suppliers

            # Cleanup Dockerfile
            rm Dockerfile
          EOF_SSH
